import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config({ path: './server/.env' });

await mongoose.connect(process.env.MONGO_URI);

const formations = [
  {
    title: "React.js Avancé",
    description: "Maîtrisez React avec les Hooks, Context API, Redux Toolkit et les meilleures pratiques de développement frontend moderne.",
    companyName: "9antra.tn",
    domain: "Développement Web",
    type: "formation",
    location: "En ligne",
    duration: "3 mois",
    skills: ["React.js", "Redux", "Hooks", "TypeScript"],
    isActive: true,
    salary: 0,
    nbrInterns: "Illimité",
    views: 0,
    image: "react",
    modules: 12,
    progress: 75,
    level: "Avancé",
    instructor: "Sami Ben Ali",
    rating: 4.8,
    students: 1240,
  },
  {
    title: "Node.js & Express",
    description: "Créez des APIs REST robustes avec Node.js, Express 5, MongoDB et les middlewares de sécurité modernes.",
    companyName: "9antra.tn",
    domain: "Backend",
    type: "formation",
    location: "En ligne",
    duration: "2 mois",
    skills: ["Node.js", "Express", "MongoDB", "JWT"],
    isActive: true,
    salary: 0,
    nbrInterns: "Illimité",
    views: 0,
    image: "node",
    modules: 10,
    progress: 45,
    level: "Intermédiaire",
    instructor: "Yassine Trabelsi",
    rating: 4.7,
    students: 980,
  },
  {
    title: "UI/UX Design",
    description: "Apprenez à créer des interfaces utilisateur modernes avec Figma, les principes du design system et l'accessibilité web.",
    companyName: "9antra.tn",
    domain: "Design",
    type: "formation",
    location: "En ligne",
    duration: "2 mois",
    skills: ["Figma", "UI/UX", "Prototypage", "Adobe XD"],
    isActive: true,
    salary: 0,
    nbrInterns: "Illimité",
    views: 0,
    image: "design",
    modules: 8,
    progress: 20,
    level: "Débutant",
    instructor: "Nour Khalil",
    rating: 4.9,
    students: 2100,
  },
  {
    title: "Git & GitHub",
    description: "Maîtrisez le versioning avec Git, les workflows professionnels GitHub, CI/CD et les Pull Requests en équipe.",
    companyName: "9antra.tn",
    domain: "DevOps",
    type: "formation",
    location: "En ligne",
    duration: "1 mois",
    skills: ["Git", "GitHub", "CI/CD", "DevOps"],
    isActive: true,
    salary: 0,
    nbrInterns: "Illimité",
    views: 0,
    image: "git",
    modules: 6,
    progress: 100,
    level: "Débutant",
    instructor: "Ahmed Mansouri",
    rating: 4.6,
    students: 3400,
  },
  {
    title: "Python & Data Science",
    description: "Initiez-vous à Python, Pandas, NumPy et Matplotlib pour l'analyse de données et la visualisation.",
    companyName: "9antra.tn",
    domain: "Data Science",
    type: "formation",
    location: "En ligne",
    duration: "3 mois",
    skills: ["Python", "Pandas", "NumPy", "Matplotlib"],
    isActive: true,
    salary: 0,
    nbrInterns: "Illimité",
    views: 0,
    image: "python",
    modules: 14,
    progress: 0,
    level: "Intermédiaire",
    instructor: "Fatma Bouaziz",
    rating: 4.8,
    students: 1560,
  },
  {
    title: "Flutter & Dart Mobile",
    description: "Développez des applications mobiles cross-platform iOS et Android avec Flutter, Dart et Firebase.",
    companyName: "9antra.tn",
    domain: "Mobile",
    type: "formation",
    location: "En ligne",
    duration: "3 mois",
    skills: ["Flutter", "Dart", "Firebase", "Mobile"],
    isActive: true,
    salary: 0,
    nbrInterns: "Illimité",
    views: 0,
    image: "flutter",
    modules: 16,
    progress: 0,
    level: "Intermédiaire",
    instructor: "Rania Hamdi",
    rating: 4.7,
    students: 890,
  },
];

const result = await mongoose.connection.collection('offers').insertMany(formations);
console.log(`✅ ${result.insertedCount} formations insérées`);
await mongoose.disconnect();
